# Generated by Django 3.0.5 on 2020-04-15 05:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_pipedata1_pipedataprocessed1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PipeData',
        ),
        migrations.DeleteModel(
            name='PipeDataProcessed',
        ),
        migrations.RenameModel('PipeData1', 'PipeData'),
        migrations.RenameModel('PipeDataProcessed1', 'PipeDataProcessed')
    ]
