# Generated by Django 3.0.5 on 2020-06-19 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20200415_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipedata',
            name='synced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pipedataprocessed',
            name='synced',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='unit',
            name='unit',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
