# Generated by Django 3.1 on 2020-09-05 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_remove_pipedataprocessed_synced'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='sync_manually',
            field=models.BooleanField(default=True),
        ),
    ]
